version: "3"
services:
  python380:
    build:
      context: ./python380
      args:
        CENTOS_VERSION: centos:centos7.9.2009
    container_name: python380_c
    tty: true
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    volumes:
      - ./code:/usr/local/code
    networks:
      - default
